# Generated by Django 4.1 on 2022-09-04 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_frequency', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('active_since', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
